{
	"name": "react-trycatch",
	"version": "1.0.0",
	"description": "High ordered component with React 16 'ErrorBoundary'",
	"main": "./build/index.js",
	"scripts": {
		"dev": "cross-env NODE_ENV=development webpack-dev-server",
		"build": "cross-env NODE_ENV=production babel ./src -d build --presets=react,env --plugins=transform-class-properties,transform-object-rest-spread --copy-files",
		"test": "echo \"Error: no test specified\" && exit 1"
	},
	"repository": {
		"type": "git",
		"url": "git+https://github.com/ahribori/react-trycatch.git"
	},
	"keywords": [
		"trycatch",
		"react",
		"error",
		"catch"
	],
	"files": [
		"build"
	],
	"author": "Ahribori",
	"license": "MIT",
	"bugs": {
		"url": "https://github.com/ahribori/react-trycatch/issues"
	},
	"homepage": "https://github.com/ahribori/react-trycatch#readme",
	"devDependencies": {
		"babel-cli": "^6.26.0",
		"babel-core": "^6.26.0",
		"babel-loader": "^7.1.2",
		"babel-plugin-transform-class-properties": "^6.24.1",
		"babel-plugin-transform-object-rest-spread": "^6.26.0",
		"babel-preset-env": "^1.6.1",
		"babel-preset-react-app": "^3.1.0",
		"cross-env": "^5.1.1",
		"webpack": "^3.8.1",
		"webpack-dev-server": "^2.9.4"
	},
	"dependencies": {
		"prop-types": "^15.6.0",
		"react": "^16.1.1",
		"react-dom": "^16.1.1"
	}
}
